# Generated by Django 3.0.3 on 2020-02-23 17:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='blog/media/photos'), upload_to='blog/media/photos'),
        ),
    ]
