# Generated by Django 3.0.3 on 2020-02-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200223_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(height_field=100, upload_to='media/article', width_field=100),
        ),
    ]
